config/routes.rb
Rails.application.routes.draw do
  root 'basic_pages#home'
  get 'basic_pages/home'
  devise_for :users
  get   'debtor_transactions/:id/approval', to: 'debtor_transactions#approval', as: 'approval_debtor_transaction'
  patch 'debtor_transactions/:id/approve_or_deny', to: 'debtor_transactions#approve_or_deny', as: 'approve_or_deny_debtor_transaction'
  get   'creditor_transactions/:id/approval', to: 'creditor_transactions#approval', as: 'approval_creditor_transaction'
  patch 'creditor_transactions/:id/approve_or_deny', to: 'creditor_transactions#approve_or_deny', as: 'approve_or_deny_creditor_transaction'
  resources :debtor_transactions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :creditor_transactions, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creditor_transaction.rb
class CreditorTransaction < ApplicationRecord
  belongs_to :debtor,     class_name: 'User', foreign_key: 'debtor_id'
  belongs_to :creditor,   class_name: 'User', foreign_key: 'creditor_id'
  validates :debtor_id,   presence: true
  validates :creditor_id,  presence: true
  validates :debt,        presence: true
  validates :debt,        numericality: { only_integer: true}
  validates :debt,        numericality: { greater_than_or_equal_to: 0 }
end

app/models/debtor_transaction.rb
class DebtorTransaction < ApplicationRecord
  belongs_to :debtor,     class_name: 'User', foreign_key: 'debtor_id'
  belongs_to :creditor,   class_name: 'User', foreign_key: 'creditor_id'
  validates :debtor_id,   presence: true
  validates :creditor_id,  presence: true
  validates :debt,        presence: true
  validates :debt,        numericality: { only_integer: true}
  validates :debt,        numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 256}
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  def home
  end
end

app/controllers/creditor_transactions_controller.rb
class CreditorTransactionsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :different_user_or_already_approve_deny_redirect_root, only: [:approval, :approve_or_deny]
  
  def index
    @transactions = CreditorTransaction.where(debtor_id: current_user.id)
  end

  def new
    @transaction = CreditorTransaction.new
  end
  
  def create
    @transaction = CreditorTransaction.new(transaction_params)
    if @transaction.save
      flash[:success] = "作成成功！"
      redirect_to creditor_transactions_url
    else
      render 'new'
    end
  end

  def edit
    @transaction = CreditorTransaction.find(params[:id])
  end

  def update
    @transaction = CreditorTransaction.find(params[:id])
    if @transaction.update_attributes(transaction_params)
      flash[:success] = "編集に成功しました"
      redirect_to creditor_transactions_url
    else
      render 'edit'
    end
  end

  def destroy
    @transaction = CreditorTransaction.find(params[:id])
    @transaction.destroy
    flash[:success] = "削除しました"
    redirect_to creditor_transactions_url
  end

  def approval
    @debtor = User.find(@transaction.debtor_id)
  end

  def approve_or_deny
    @transaction = CreditorTransaction.find(params[:id])
    if @transaction.update_attributes(approve_or_deny_transaction_params)
      if @transaction.approval == true
        flash[:success] = "承認しました"
        redirect_to root_url
      else @transaction.approval == false
        flash[:success] = "拒否しました"
        redirect_to root_url
      end
    else
      render 'approval'
    end
  end

  private
    def transaction_params
      params.require(:creditor_transaction).permit(:debtor_id, :creditor_id, :debt, :repayment)
    end

    def approve_or_deny_transaction_params
      params.require(:creditor_transaction).permit(:approval)
    end

    def different_user_or_already_approve_deny_redirect_root
      @transaction = CreditorTransaction.find(params[:id])
        if @transaction.creditor_id != current_user.id
          redirect_to root_url
        elsif @transaction.approval == true
          redirect_to root_url
        elsif @transaction.approval == false
          redirect_to root_url
        end
    end
end

app/controllers/debtor_transactions_controller.rb
class DebtorTransactionsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update]
  before_action :different_user_or_already_approve_deny_redirect_root, only: [:approval, :approve_or_deny]

  def index
    @transactions = DebtorTransaction.where(creditor_id: current_user.id)
  end
  
  def new
    @transaction = DebtorTransaction.new
  end
  
  def create
    @transaction = DebtorTransaction.new(transaction_params)
    if @transaction.save
      flash[:success] = "作成成功！"
      redirect_to debtor_transactions_url
    else
      render 'new'
    end
  end

  def edit
    @transaction = DebtorTransaction.find(params[:id])
  end

  def update
    @transaction = DebtorTransaction.find(params[:id])
    if @transaction.update_attributes(transaction_params)
      flash[:success] = "編集に成功しました"
      redirect_to debtor_transactions_url
    else
      render 'edit'
    end
  end

  def destroy
    @transaction = DebtorTransaction.find(params[:id])
    @transaction.destroy
    flash[:success] = "削除しました"
    redirect_to debtor_transactions_url
  end

  def approval
    @creditor = User.find(@transaction.creditor_id)
  end

  def approve_or_deny  
    if @transaction.update_attributes(approve_or_deny_transaction_params)
      if @transaction.approval == true
        flash[:success] = "承認しました"
        redirect_to root_url
      else @transaction.approval == false
        flash[:success] = "拒否しました"
        redirect_to root_url
      end
    else
      render 'approval'
    end
  end

  private

    def transaction_params
      params.require(:debtor_transaction).permit(:debtor_id, :creditor_id, :debt, :repayment)
    end

    def approve_or_deny_transaction_params
      params.require(:debtor_transaction).permit(:approval)
    end

    def different_user_or_already_approve_deny_redirect_root
      @transaction = DebtorTransaction.find(params[:id])
        if @transaction.debtor_id != current_user.id
          redirect_to root_url
        elsif @transaction.approval == true
          redirect_to root_url
        elsif @transaction.approval == false
          redirect_to root_url
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/helpers/creditor_transactions_helper.rb
module CreditorTransactionsHelper
end

app/helpers/debtor_transactions_helper.rb
module DebtorTransactionsHelper
end

app/views/basic_pages/home.html.erb
<h1>ログイン</h1>

<% if user_signed_in? %>
  <h2> 現在 <%= current_user.name %> さんがログインしています </h2>
  <h4> メールアドレス： <%= current_user.email %> </h4>
  <p><%= link_to "貸した人一覧", debtor_transactions_path %></p>
  <p><%= link_to "借りた人一覧", creditor_transactions_path %></p>
  <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
<% else %>
  <h2> 現在ログインしていません </h2>
  <p><%= link_to "ログイン", new_user_session_path, class: 'post' %></p>
  <p><%= link_to "新規登録", new_user_registration_path, class: 'post' %></p>
<% end %>

app/views/creditor_transactions/approval.html.erb
<h2><%= @debtor.name %>さんからあなたに以下の内容で承認依頼が届いています！</h2>

<h4>・<%= @debtor.name %> さんが あなたから <%= @transaction.debt %> 円 を借りている</h4>

<%= form_for(@transaction, url: approve_or_deny_creditor_transaction_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
   
    <%= f.label :approval, "承認" %>
    <%= f.radio_button :approval, true %> <br />
    <%= f.label :approval, "拒否" %>
    <%= f.radio_button :approval, false %> <br />
  
    <%= f.submit "送信"%>
  </div>
<% end %>

app/views/creditor_transactions/edit.html.erb
<%= form_for(@transaction, url: creditor_transaction_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
  
      <%= f.hidden_field :debtor_id, :value => current_user.id %>
  
      <%= f.label :creditor_id, "借りる相手" %> <br />
      <%= f.select :creditor_id,
            options_from_collection_for_select(User.where.not(id: current_user.id), :id, :name),
            {
            class: "form-control", :prompt => "選択できます"
            } 
      %><br />
  
      <%= f.label :debt, "金額" %> <br />
      <%= f.number_field :debt, class: "form-control" %> <br />
      
      <%#= f.label :repayment, "返済済みかどうか" %> <br />
      <%#= f.check_box :repayment, {}, "true", "false"  %> <br />
  
      <%= f.submit "作成"%>
    </div>
  <% end %>

app/views/creditor_transactions/index.html.erb
<h2><%= current_user.name %>さんが借りた記録</h4>
<% i = 0 %>
<% if @transactions.any? %>
  <% @transactions.each do |transaction| %>
    <% creditor = User.find(transaction.creditor_id) %>
    <p>借りた人：　　<%= creditor.name %></p>
    <p>借りた金額：　<%= transaction.debt %></p>
    <p><%= link_to "編集", edit_creditor_transaction_path(id: transaction.id) %></p>
    <p><%= link_to "削除", creditor_transaction_path(id: transaction.id), method: :delete %></p>
    <% if transaction.approval.nil? %>
      <% i += 1 %>
      <textarea id="creditor-clipboard-<%= current_user.id %>-<%= i %>">
        <%= "#{approval_creditor_transaction_url(id: transaction.id)}" %>
      </textarea>
      <button class="btn btn-secondary clipboard-btn" data-clipboard-action="copy" data-clipboard-target="#creditor-clipboard-<%= current_user.id %>-<%= i %>">
        承認用のリンクをコピー
      </button>
    <% else %>
      <% if transaction.approval %>
        <p>承認済み</p>
      <% else %>        
        <p>拒否されました</p>
      <% end %>
    <% end %>
    <hr>
  <% end %>
<% else %>
  <p>現在借りていません！</p>
<% end %>

app/views/creditor_transactions/new.html.erb
<%= form_for(@transaction, url: creditor_transactions_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
  
      <%= f.hidden_field :debtor_id, :value => current_user.id %>
  
      <%= f.label :creditor_id, "借りる相手" %> <br />
      <%= f.select :creditor_id,
            options_from_collection_for_select(User.where.not(id: current_user.id), :id, :name),
            {
            class: "form-control", :prompt => "選択できます"
            } 
      %><br />
  
      <%= f.label :debt, "金額" %> <br />
      <%= f.number_field :debt, class: "form-control" %> <br />
      
      <%#= f.label :repayment, "返済済みかどうか" %> <br />
      <%#= f.check_box :repayment, {}, "true", "false"  %> <br />
  
      <%= f.submit "作成"%>
    </div>
  <% end %>

app/views/debtor_transactions/approval.html.erb
<h2><%= @creditor.name %>さんからあなたに以下の内容で承認依頼が届いています！</h2>

<h4>・<%= @creditor.name %> さんが あなたに <%= @transaction.debt %> 円 を貸している</h4>

<%= form_for(@transaction, url: approve_or_deny_debtor_transaction_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
   
    <%= f.label :approval, "承認" %>
    <%= f.radio_button :approval, true %> <br />
    <%= f.label :approval, "拒否" %>
    <%= f.radio_button :approval, false %> <br />
  
    <%= f.submit "送信"%>
  </div>
<% end %>

app/views/debtor_transactions/edit.html.erb
<%= form_for(@transaction, url: debtor_transaction_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
  
      <%= f.hidden_field :creditor_id, :value => current_user.id %>
  
      <%= f.label :debtor_id, "貸す相手" %> <br />
      <%= f.select :debtor_id,
            options_from_collection_for_select(User.where.not(id: current_user.id), :id, :name),
            {
            class: "form-control", :prompt => "選択できます"
            } 
      %><br />
  
      <%= f.label :debt, "金額" %> <br />
      <%= f.number_field :debt, class: "form-control" %> <br />
      
      <%#= f.label :repayment, "返済済みかどうか" %> <br />
      <%#= f.check_box :repayment, {}, "true", "false"  %> <br />
  
      <%= f.submit "作成"%>
    </div>
  <% end %>

app/views/debtor_transactions/index.html.erb
<h2><%= current_user.name %>さんが貸した記録</h4>
<% i = 0 %>
<% if @transactions.any? %>
  <% @transactions.each do |transaction| %>
    <% debtor = User.find(transaction.debtor_id) %>
    <p>貸した人：　　<%= debtor.name %></p>
    <p>貸した金額：　<%= transaction.debt %></p>
    <p><%= link_to "編集", edit_debtor_transaction_path(id: transaction.id) %></p>
    <p><%= link_to "削除", debtor_transaction_path(id: transaction.id), method: :delete %></p>
    <% if transaction.approval.nil? %>
      <% i += 1 %>
      <textarea id="debtor-clipboard-<%= current_user.id %>-<%= i %>">
        <%= "#{approval_debtor_transaction_url(id: transaction.id)}" %>
      </textarea>
      <button class="btn btn-secondary clipboard-btn" data-clipboard-action="copy" data-clipboard-target="#debtor-clipboard-<%= current_user.id %>-<%= i %>">
        承認用のリンクをコピー
      </button>
    <% else %>
      <% if transaction.approval %>
        <p>承認済み</p>
      <% else %>        
        <p>拒否されました</p>
      <% end %>
    <% end %>
    <hr>
  <% end %>
<% else %>
  <p>現在貸している人はいません！</p>
<% end %>

app/views/debtor_transactions/new.html.erb
<%= form_for(@transaction, url: debtor_transactions_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  
    <%= f.hidden_field :creditor_id, :value => current_user.id %>

    <%= f.label :debtor_id, "貸す相手" %> <br />
    <%= f.select :debtor_id,
      options_from_collection_for_select(User.where.not(id: current_user.id), :id, :name),
        {
          class: "form-control", :prompt => "選択できます"
        } 
    %><br />
  
    <%= f.label :debt, "金額" %> <br />
    <%= f.number_field :debt, class: "form-control" %> <br />
      
    <%#= f.label :repayment, "返済済みかどうか" %> <br />
    <%#= f.check_box :repayment, {}, "true", "false"  %> <br />
  
    <%= f.submit "作成"%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KashitayoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "ホーム", root_path, id: "logo" %>
        <nav class="navbar-right">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            　<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to "貸す！",   new_debtor_transaction_path %></li>
              <li><%= link_to "借りる！", new_creditor_transaction_path %></li>
            <% else %>
              <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
              <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      このフォームには<%= object.errors.count %>個のエラーがあります
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>